# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-21 19:16
from __future__ import unicode_literals

import Upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='img',
            field=models.ImageField(max_length=255, storage=Upload.models.ImageFilesStorage(), upload_to='shop/img/'),
        ),
    ]
