# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-21 19:29
from __future__ import unicode_literals

import Upload.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0002_auto_20181121_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=255, storage=Upload.models.ImageFilesStorage(), upload_to='shop/img')),
                ('type', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.RemoveField(
            model_name='shop',
            name='img',
        ),
        migrations.AddField(
            model_name='img',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Upload.Shop'),
        ),
    ]
